# Generated by Django 4.1.3 on 2025-05-24 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_specialty_alter_doctors_specialty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="doctor",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="patient",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
