# Generated by Django 4.1.3 on 2025-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_doctors_user_alter_patients_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="consult_fee",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="doctors",
            name="consult_hour",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
