# Generated by Django 5.2.1 on 2025-05-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_blogs_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="description",
            field=models.TextField(max_length=50),
        ),
    ]
