# Generated by Django 5.2.1 on 2025-05-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_blogs_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="summary",
            field=models.TextField(max_length=50),
        ),
    ]
